### ISSUE TITLE
[DEMO] ASPNETCORE MVC

### ISSUE THREAD

**Issue by ghost** [StefH/AspNetCore.Security.Auth0#2]
Hi @StefH,

Where can I find a aspnetcore sample/demo of this library in action?

**Comment by StefH** [comment]
Hello @nicotravassos.

I did update the readme + added a WIKI page, please take a look there.

For a demo, you can already take a look here
https://github.com/StefH/QboxNext/tree/master/src-server/QboxNext.Server.Frontend

This includes a SPA Angular + C# WebApi project,

If I have more time, I'll create a sample in this repository.

**Comment by ghost** [comment]
Thank you @StefH
